# Generated by Django 4.0 on 2021-12-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrowZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=4)),
                ('lowest_temp', models.IntegerField()),
                ('average_last_frost', models.DateField()),
                ('average_first_frost', models.DateField()),
            ],
        ),
    ]
