# Generated by Django 4.0 on 2021-12-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growzone',
            name='id',
        ),
        migrations.AlterField(
            model_name='growzone',
            name='average_first_frost',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='growzone',
            name='average_last_frost',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='growzone',
            name='zone_name',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
