# Generated by Django 4.0 on 2021-12-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_growzone_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growzone',
            name='average_first_frost',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='growzone',
            name='average_last_frost',
            field=models.DateField(null=True),
        ),
    ]
